### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#100]
## 1

https://soup.wordsinspace.net/the-new-everyday/ 
![image](https://user-images.githubusercontent.com/10440556/91076816-0bcaeb80-e60e-11ea-8a38-f1395cedb0c9.png)
![image](https://user-images.githubusercontent.com/10440556/91076833-12f1f980-e60e-11ea-8a59-2b11ad8f8511.png)

file name: https://wordsinspace.net/shannon/wp-content/uploads/2017/07/candy_land_04_b_1000_its_nice_that.jpg 

## 2
https://soup.wordsinspace.net/bad-signal/
![image](https://user-images.githubusercontent.com/10440556/91077246-bcd18600-e60e-11ea-9106-4a1ef4b57def.png)
![image](https://user-images.githubusercontent.com/10440556/91077259-c35ffd80-e60e-11ea-9200-d82e66eb3c58.png)
file name: https://wordsinspace.net/shannon/wp-content/uploads/2017/07/freqspectrum.gif

## 3
https://soup.wordsinspace.net/plurality-in-place-activating-public-places-in-seattle-2/
![image](https://user-images.githubusercontent.com/10440556/91077364-ef7b7e80-e60e-11ea-8aff-ae93a8ff93bd.png)
![image](https://user-images.githubusercontent.com/10440556/91077385-f6a28c80-e60e-11ea-884d-40186cdc1696.png)
file name: https://wordsinspace.net/shannon/wp-content/uploads/2017/07/maxresdefault.jpg

## 4
https://soup.wordsinspace.net/datacase/
![image](https://user-images.githubusercontent.com/10440556/91077689-7d576980-e60f-11ea-8dd5-cecfbfe2ce8b.png)
![image](https://user-images.githubusercontent.com/10440556/91077707-87796800-e60f-11ea-986a-efcaa43c6963.png)
file name: https://wordsinspace.net/shannon/wp-content/uploads/2017/07/matternimage.jpg 

## 5
https://soup.wordsinspace.net/graduate-institute-of-design-ethnography-social-thought-2014-2015/
![image](https://user-images.githubusercontent.com/10440556/91077972-f0f97680-e60f-11ea-963c-697ad719c3da.png)
![image](https://user-images.githubusercontent.com/10440556/91077961-ec34c280-e60f-11ea-8581-827cd4550c79.png)
file name: https://wordsinspace.net/shannon/wp-content/uploads/2017/07/gidest.jpg

## 6 
https://soup.wordsinspace.net/understanding-media-studies-speaker-series-2014-2015/
![image](https://user-images.githubusercontent.com/10440556/91078062-125a6280-e610-11ea-889f-5240e558749a.png)
![image](https://user-images.githubusercontent.com/10440556/91078040-0b335480-e610-11ea-929f-81e7a61e294b.png)
file name: https://wordsinspace.net/shannon/wp-content/uploads/2017/07/ums_newschool_spr2015lectureseries3.jpg

## 7 
https://soup.wordsinspace.net/catastrophe-slam-2009/
![image](https://user-images.githubusercontent.com/10440556/91078151-374ed580-e610-11ea-9e0b-1583ad5dcf39.png)
![image](https://user-images.githubusercontent.com/10440556/91078127-3027c780-e610-11ea-84d6-74580f6936a4.png)
file name: https://wordsinspace.net/shannon/wp-content/uploads/2017/07/catastropheslam.jpg

## 8 
https://soup.wordsinspace.net/public-information/
![image](https://user-images.githubusercontent.com/10440556/91078258-606f6600-e610-11ea-9a11-a8e7385f9afd.png)
![image](https://user-images.githubusercontent.com/10440556/91078271-67967400-e610-11ea-9675-0fbc79bfc4b8.png)
file name: https://wordsinspace.net/shannon/wp-content/uploads/2017/07/image-3.jpg

## 9 
https://soup.wordsinspace.net/information-professional-dutch-interview/
![image](https://user-images.githubusercontent.com/10440556/91078342-7ed56180-e610-11ea-9d69-878dc208c623.png)
![image](https://user-images.githubusercontent.com/10440556/91078319-78df8080-e610-11ea-9cdd-94953513758b.png)
file name: https://wordsinspace.net/shannon/wp-content/uploads/2017/07/pages-from-ip201605-voorproefje-1.jpg

## 10 
https://soup.wordsinspace.net/bookshelves-to-big-data-archaeologies-of-knowledge/
![image](https://user-images.githubusercontent.com/10440556/91079217-c3adc800-e611-11ea-9451-1e7a25f1e447.png)
![image](https://user-images.githubusercontent.com/10440556/91079227-c7d9e580-e611-11ea-844d-84d5bd7bff99.png)
https://wordsinspace.net/shannon/wp-content/uploads/2017/07/ff_googleinfrastructure2_large.jpg

**Comment by rokeby** [comment]
It seems like these are missing from the HTML, possibly accidentally removed from an import fix? can replace manually.

<img width="1440" alt="Screenshot 2020-08-28 at 23 46 16" src="https://user-images.githubusercontent.com/23423665/91620785-de24d000-e988-11ea-9c13-ad678489b0c1.png">
<img width="377" alt="Screenshot 2020-08-28 at 23 44 14" src="https://user-images.githubusercontent.com/23423665/91620794-e250ed80-e988-11ea-9853-a7e76da1f7c4.png">
<img width="375" alt="Screenshot 2020-08-28 at 23 43 38" src="https://user-images.githubusercontent.com/23423665/91620795-e2e98400-e988-11ea-9679-543accf51990.png">
