### ISSUE TITLE
overly-wide issues with some pages on iOS safari mobile

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#105]
https://soup.wordsinspace.net/2011/03/wait-i-did-that/
![IMG_0303](https://user-images.githubusercontent.com/5625731/91115980-5f165b80-e659-11ea-8ab4-a0fc45704f3a.PNG)

https://soup.wordsinspace.net/2011/08/revisiting-craft-i-teaching-the-connections-between-thinking-and-making/
![IMG_0306](https://user-images.githubusercontent.com/5625731/91116055-82d9a180-e659-11ea-9230-c0d624533884.PNG)

https://soup.wordsinspace.net/2012/05/media-materiality-final-projects/
![IMG_0312](https://user-images.githubusercontent.com/5625731/91116082-95ec7180-e659-11ea-9564-b783d97c2eb9.jpg)

**Comment by rokeby** [comment]
rogue inline special privileged shits
