### ISSUE TITLE
thumbnail images not coming up on hover when tags selected

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#110]
![Screen Shot 2020-08-26 at 16 01 48](https://user-images.githubusercontent.com/5625731/91351036-9568ed80-e7b5-11ea-8a81-3d72edb12e1f.png)

**Comment by rokeby** [comment]
ach, this has to do with failing to attach (and subsequent "mixed-content" error) again. will look at why that might be happening when tag selection triggers refresh.

**Comment by samtous** [comment]
you sure? this only happens when tags are selected; fine otherwise

**Comment by rokeby** [comment]
not looking right now but in inspector it's a difference between "could not load image" from an <img src="... .jpg" > and when it does load, the more embedded HTML of <picture><source> etc.

**Comment by samtous** [comment]
this got fixed when the CORS error got fixed
