### ISSUE TITLE
small fix -- spaces at the start of lines in longer tags

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#117]
<img width="246" alt="image" src="https://user-images.githubusercontent.com/5625731/91880682-6091e600-ec4e-11ea-8876-804c6eaf4ce2.png">
perhaps something on the frontend to replace a space with a newline?

**Comment by samtous** [comment]
hmmmmmmmm this is _not_ fixed by adding a newline regex to replace spaces, wondering if it's to do with the button shape?

**Comment by Kallirroi** [comment]
I can't run this locally but try adding the `text-indent: 5px` or sth like that to the wrapper component

**Comment by rokeby** [comment]
:)
