### ISSUE TITLE
Missing thumbnails

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#12]

**Comment by Kallirroi** [comment]
![image](https://user-images.githubusercontent.com/10440556/89053623-84979a00-d325-11ea-9c75-80e48a59accb.png)

**Comment by Kallirroi** [comment]
Update: some of them are GIFs, some are missing 
![image](https://user-images.githubusercontent.com/10440556/89071423-b2400b80-d344-11ea-9721-28d72e195323.png)

**Comment by agnescameron** [comment]
I went through all the posts, and these are the ones without thumbnails:

— maps as media http://localhost:8000/teaching/maps-as-media/ 
— bad signal http://localhost:8000/publications/bad-signal/ 
— mapping time http://localhost:8000/2015/10/25/mapping-time/ 
— maps as media http://localhost:8000/2015/07/07/maps-as-media-sketching-out-the-syllabus/ 
— advisee accolades http://localhost:8000/2014/05/22/advisee-accolades-ii/
— http://localhost:8000/2012/09/07/urban-media-archaeology-now-even-more-awesome-in-my-humble-opinion/ 
— http://localhost:8000/2012/07/20/infrastructural-tourism/ 
— http://localhost:8000/2010/12/17/not-so-delicious-quite-bitter-actually/ 
— http://localhost:8000/2010/12/07/the-other-spring-class/ 
— http://localhost:8000/2010/09/09/notes-lists-and-everyday-inscriptions-issue-of-the-new-everyday/ 
— http://localhost:8000/2010/08/20/abstracts-annotated-bibliographies/ 
— http://localhost:8000/2010/07/19/urban-media-archaeology/

I think we can just resolve this manually after the final import!
