### ISSUE TITLE
Post content has every new word capitalised on the frontend

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/wordsinspace#13]
....but not in the wordpress

![Screen Shot 2020-08-06 at 10 27 05](https://user-images.githubusercontent.com/16444898/89543876-79ce8080-d7cf-11ea-8c26-aa376c27af03.png)
![Screen Shot 2020-08-06 at 10 27 36](https://user-images.githubusercontent.com/16444898/89543877-7a671700-d7cf-11ea-8c91-7a5ac696b545.png)

**Comment by agnescameron** [comment]
or in the graphql query....

![Screen Shot 2020-08-06 at 10 32 42](https://user-images.githubusercontent.com/16444898/89544531-3d4f5480-d7d0-11ea-9f53-09c140eb944d.png)

**Comment by agnescameron** [comment]
<img width="511" alt="Screen Shot 2020-08-06 at 10 39 07" src="https://user-images.githubusercontent.com/16444898/89545224-15142580-d7d1-11ea-9b6c-15450439a6f7.png">
ahaaaa

**Comment by agnescameron** [comment]
[fixed](https://github.com/Kallirroi/wordsinspace/commit/eeac525c95da4b8657f095d6d9bd5ce154c2293a)

**Comment by Kallirroi** [comment]
![image](https://user-images.githubusercontent.com/10440556/89572666-6fc07800-d7f7-11ea-96e0-7b722c13fca5.png)
btw this is Figma's fault somehow? so weird

**Comment by agnescameron** [comment]
yeah it's `text-transform: capitalize` in the CSS
