### ISSUE TITLE
possible caching bug on firefox?

### ISSUE THREAD

**Issue by agnescameron** [Kallirroi/wordsinspace#16]
occasional issue on firefox where, after half an hour or so on the site doesn't load any more -- it might be a caching thing. So far only noticed this on local build

**Comment by agnescameron** [comment]
`Source map error: Error: Invalid URL: .
Resource URL: blob:http://localhost:8000/c026c0c6-b394-5d42-b988-0feee5f89fd9`

**Comment by Kallirroi** [comment]
looks like something clearing cache would help with yes

**Comment by Kallirroi** [comment]
has this happened recently?

**Comment by samtous** [comment]
no, not for a while! I was gonna stress test tonight on remote and local to be sure though

**Comment by Kallirroi** [comment]
ok closing for now, we can reopen if it happens again.
