### ISSUE TITLE
List of things Shannon needs to do

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#17]
**Before release**
- apply final Tags?
- migrate Uncategorized?
- migrate Research?
- Classes vs Teaching - **potential big issue if one of them is a tag - given that tags don't have their URLs. Has she realized that?**
- migrate Talks?
- edit dates so that they agree with what she puts in the title
- Related posts/pages strategy

**Moving forward**
- citations

**Comment by samtous** [comment]
Shannon is offering to go in and change dates manually in wordpress (!)
