### ISSUE TITLE
misplaced and very funny looking Categories

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#20]
![image](https://user-images.githubusercontent.com/10440556/89700352-789a7200-d8fb-11ea-8171-99a877ad3a4d.png)

**Comment by rokeby** [comment]
Not sure when these happened but not seeing this across any browser now?

**Comment by Kallirroi** [comment]
![image](https://user-images.githubusercontent.com/10440556/89793360-c8dc2480-daf3-11ea-8176-6bd9db3072c6.png)

its still like this for me :/

**Comment by Kallirroi** [comment]
The mystery continues:

My Chrome:
![image](https://user-images.githubusercontent.com/10440556/89811487-bf12eb00-db0c-11ea-9527-8fe42aafb6f4.png)

My Safari:
![image](https://user-images.githubusercontent.com/10440556/89811515-c639f900-db0c-11ea-903f-9089eb789bf4.png)

My Firefox: 
![image](https://user-images.githubusercontent.com/10440556/89811550-d3ef7e80-db0c-11ea-9016-893bbbc9bc6b.png)

**Comment by Kallirroi** [comment]
Looks fine now for me both locally + deployed versions!
