### ISSUE TITLE
getRelated error for tags without tag.pages or tag.posts

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#24]
Certain posts such as http://localhost:8000/sonic-archaeologies/ are getting this error:

![work Words in Space](https://user-images.githubusercontent.com/5625731/89734016-60c00c80-da27-11ea-8404-40b16d83db20.png)

So it seems like while tag returns an object, certain tags don’t have tag.pages and tag.posts value throwing up an error for getRelated. Have temporarily fixed with this.

<img width="1038" alt="export const getRelated = (tags, title)" src="https://user-images.githubusercontent.com/5625731/89734052-9a911300-da27-11ea-836b-f21f230181c1.png">

**Comment by Kallirroi** [comment]
yeah its because of the localhost pointing to different WP instances I think - should not be happening once we point it to only remote version.

**Comment by agnescameron** [comment]
speaking of which, running import now 🤞🏼

**Comment by samtous** [comment]
speaking of which, running import on the server now 🤞🏼

**Comment by Kallirroi** [comment]
Should be fixed https://github.com/Kallirroi/wordsinspace/commit/3d91f3759180961a19f0c69ef7e70219fa11c6a4
