### ISSUE TITLE
possible utf-8 encoding bug on main page?

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#25]
![Screen Shot 2020-08-09 at 15 31 58](https://user-images.githubusercontent.com/5625731/89740315-a09de880-da55-11ea-9389-9b039f83b50e.png)
<img width="689" alt="Screen Shot 2020-08-09 at 15 32 14" src="https://user-images.githubusercontent.com/5625731/89740316-a1367f00-da55-11ea-8300-3cf2405de460.png">
<img width="689" alt="Screen Shot 2020-08-09 at 15 32 28" src="https://user-images.githubusercontent.com/5625731/89740317-a1367f00-da55-11ea-9119-e40aaaa2a2ea.png">
 ampersands behaving weirdly: fine in wp editor and on /work, but somehow not on the main page

**Comment by Kallirroi** [comment]
its probably because they arrive through a different "route" (the Menu) - I will try playing around with that a bit

**Comment by samtous** [comment]
huh maybe it's because i tried to get rid of this artifact explicitly in the xml... gonna go back to leaving it alone, i've only noticed this on more recent imports
