### ISSUE TITLE
text overflowing 'related' orbs

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#29]

**Comment by samtous** [comment]
![Screen Shot 2020-08-11 at 20 34 26](https://user-images.githubusercontent.com/5625731/90039540-c49b3d00-dc94-11ea-985e-ad8295469192.png)

needs a '...' or something after a character limit?

**Comment by Kallirroi** [comment]
![image](https://user-images.githubusercontent.com/10440556/90074070-68eaa700-dcc8-11ea-8ad2-d178981f3edf.png)
I think the design is like that?

**Comment by samtous** [comment]
it looks nice on the design, but the majority of the ones i've seen are kind of uneven and don't look so great... Just something that can adapt a bit to a variety of text and some (extremely) long titles

**Comment by rokeby** [comment]
<img width="387" alt="Screenshot 2020-08-13 at 17 01 30" src="https://user-images.githubusercontent.com/23423665/90158458-ebd23700-dd86-11ea-88a3-c0af2b032b57.png">
<img width="383" alt="Screenshot 2020-08-13 at 17 01 23" src="https://user-images.githubusercontent.com/23423665/90158461-ec6acd80-dd86-11ea-9ae5-02747f60db5f.png">

settled on a middle ground with 2px smaller font
