### ISSUE TITLE
text is hard to read

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#30]
mb just needs to be bigger, and have some more contrast

![Screen Shot 2020-08-11 at 20 44 00](https://user-images.githubusercontent.com/5625731/90039647-ef859100-dc94-11ea-82fa-58636959fbe5.png)

**Comment by rokeby** [comment]
.content font to size 22px and lineheight 34 per Figma feels much better now

![Screenshot 2020-08-13 at 01 49 32](https://user-images.githubusercontent.com/23423665/90082319-622f5480-dd07-11ea-9319-fd62e639f6fa.png)
