### ISSUE TITLE
CSS fixes for 'scroll up' arrows

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#33]

**Comment by rokeby** [comment]
<img width="620" alt="Screenshot 2020-08-16 at 19 16 50" src="https://user-images.githubusercontent.com/23423665/90341152-0a3d6a00-dff5-11ea-9eff-52339c829d7b.png">

confused about what this issue is about -- this is how it looks now

**Comment by Kallirroi** [comment]
its about implementing Sam's design, so we're good!
