### ISSUE TITLE
finalize reader layout

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#36]
![Screen Shot 2020-08-11 at 20 47 49](https://user-images.githubusercontent.com/5625731/90039746-10e67d00-dc95-11ea-9ebe-9e1a5cf7ec11.png)

NB -- this might be a combination of a responsiveness question and a general spacing question.... this looks so crowded as the related articles maybe wanna live a bit further down, but also it's due to lines breaking etc.

**Comment by rokeby** [comment]
<img width="1440" alt="Screenshot 2020-08-13 at 01 42 59" src="https://user-images.githubusercontent.com/23423665/90081916-673fd400-dd06-11ea-877d-235df342383c.png">


How it looks currently: do you think it needs more spacing, and perhaps for related to move below the image gallery line? (this screenshot doesn't show working image gallery so image is bigger than it should be).

**Comment by rokeby** [comment]
<img width="1440" alt="Screenshot 2020-08-17 at 15 14 51" src="https://user-images.githubusercontent.com/23423665/90405959-66a79480-e09c-11ea-99d8-57424d9ff514.png">

-layout- is done, related moved downwards, still ironing out minor inline bugs as we review more articles
