### ISSUE TITLE
actionMonitor

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#4]
![image](https://user-images.githubusercontent.com/10440556/86514288-7bc3af00-bddf-11ea-9a8f-80af57e6b825.png)

**Comment by Kallirroi** [comment]
I think this happens when the connection between localhost and remote Wordpress drops.

**Comment by Kallirroi** [comment]
Also happened when accessing `http://localhost:8000/sounding-the-commons-2018`

**Comment by agnescameron** [comment]
this also appears as an error during import! Gonna look into this

**Comment by Kallirroi** [comment]
maybe having to do with authentication to wordpress? I think it just happened to my gatsby dev when I logged into my local Wordpress `wp-admin`.

**Comment by agnescameron** [comment]
this is no longer an issue I think?
