### ISSUE TITLE
still getting [vc] junk? 🤔

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#41]
![image](https://user-images.githubusercontent.com/10440556/90041416-41c7b180-dc97-11ea-8928-655aabaebc5b.png)

**Comment by samtous** [comment]
Hm, you shouldn't be: here it is in the wordpress import: 
https://importiv.wordsinspace.net/how-to-run-a-city-like-amazon-and-other-fables/
and on the remote build I have to test redirects:
https://wordsinspace.netlify.app/how-to-run-a-city-like-amazon-and-other-fables/ (from an old version of the code but you get the idea)

**Comment by Kallirroi** [comment]
![image](https://user-images.githubusercontent.com/10440556/90075561-b3215780-dccb-11ea-9a15-9e596ca52a8b.png)

Hm can you check this one on `importIV` ?

**Comment by samtous** [comment]
![Screen Shot 2020-08-12 at 19 06 36](https://user-images.githubusercontent.com/5625731/90076957-f630fa00-dcce-11ea-9945-c4eaa192b32e.png)

no, can you try clearing your cache again?

**Comment by samtous** [comment]
![image](https://user-images.githubusercontent.com/5625731/90077046-22e51180-dccf-11ea-98b1-2e9bb739f15c.png)
here it is locally (same import file)

**Comment by samtous** [comment]
btw I know that these aren't in importiv cause i ctrl+F the import doc for `vc_`, and there's not any there

**Comment by Kallirroi** [comment]
Yep looks great now.
