### ISSUE TITLE
find GIFs that get ignored during deployment?

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#42]
![image](https://user-images.githubusercontent.com/10440556/90074749-dcd97f00-dcc9-11ea-9f41-330db086db00.png)

**Comment by samtous** [comment]
would a good outcome for this just be to convert .gif files to pngs from their first frame? // is this something that could be an issue on gatsby, might be easy for them to fix

**Comment by Kallirroi** [comment]
these images are there, and apparently these are warnings, so closing this
