### ISSUE TITLE
Upcoming events is empty

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#43]
which one are we supposed to use?

**Comment by samtous** [comment]
are we keeping either of these? (//how would shannon add to them?)

**Comment by Kallirroi** [comment]
![image](https://user-images.githubusercontent.com/10440556/90151453-b90f4b00-dd54-11ea-83bd-62d14a26ba53.png)

we should be keeping at least one (I assume /upcoming-events/) - but why is it empty tho? 

Here is how it should look like: https://wordsinspace.net/shannon/presentations/upcoming-events/

**Comment by samtous** [comment]
I assumed it was empty for the same reason that her original `/presentations` page was empty: it was normally filled with things tagged upcoming-events?

**Comment by Kallirroi** [comment]
no it was never a category or a tag, just a page. She keeps editing it I think and manually adding text: 
![image](https://user-images.githubusercontent.com/10440556/90154520-35575d80-dd58-11ea-82d6-6a9caa31b8b8.png)

**Comment by samtous** [comment]
oh wait got it: it's a redirects issue 
https://wordsinspace.vercel.app/presentations/upcoming-events/ -> the correct one

I think the one at /upcoming-events _is_ auto-generated:
https://wordsinspace.net/shannon/upcoming-events/
