### ISSUE TITLE
Final import: remove Uncategorized

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#54]
I am confused by her email: 

`The “Uncategorized” category was often checked by default when I posted a blog post — so I think some of those “Uncategorized” posts are labeled as such in error. In other cases, “Uncategorized” was for more personal items — which would, under the new system, be categorized under “Et Cetera” or “Diary.”`

**Comment by samtous** [comment]
ok: I guess what she's saying is that most things in Uncategorized should be in 'blog', and I can move them now. 

et cetera and diary are parent classes, and I can recommend she add those as she likes. The main question to me is how 'uncategorized' is currently being rendered: is it possible to just leave it off? I think we should make sure that we don't cause an error if she _does_ add something by uncategorized (as it happens automatically if you don't add a category to a post)

**Comment by samtous** [comment]
@rokeby there is still the need for this category to exist, but perhaps we don't show in the sidebar?

**Comment by rokeby** [comment]
> @rokeby there is still the need for this category to exist, but perhaps we don't show in the sidebar?

I was v much assuming they were on the way out, along with "research" -- I haven't touched it since I didnt' want to mess with wp-admin much, but I assume we just remove them by removing them as Categories in WP? Then the query would no longer throw it up for the side bar?
