### ISSUE TITLE
Final import: remove Research from Categories

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#55]
From her email: 

`The “Research”category can be eliminated; in some cases these are posts about “Academia,” and in other cases they’re simply notices about upcoming or past talks + publications`

**Comment by samtous** [comment]
ok -- looked into this and you can't 'remove' something from a category without putting it in a diff. category, even if that category is 'Uncategorised'... i'm thinking to just add to 'Uncategorised' for now tho this also begs the question, what to do with 'Uncategorised'?
