### ISSUE TITLE
listItem thumbnail styling stops applying when a tag is selected

### ISSUE THREAD

**Issue by rokeby** [Kallirroi/wordsinspace#59]
![Screenshot 2020-08-13 at 01 37 07](https://user-images.githubusercontent.com/23423665/90081696-e8e33200-dd05-11ea-84c3-6c4473755016.png)

on hover images sizes are fine on /work but thumbnail styling in listItem.js seems to stop effecting on tag selection

**Comment by samtous** [comment]
this might be because I removed the `max-width:100%` from `.content img {}` earlier (it was v general and hurting the slideshows...) if that is the issue, is there another way to address thumbnail images?

**Comment by rokeby** [comment]
> this might be because I removed the `max-width:100%` from `.content img {}` earlier (it was v general and hurting the slideshows...) if that is the issue, is there another way to address thumbnail images?

alas don't think it's that since these images don't fall under `.content`, but it seeks likely it has something to do with `gatsby-image` listImage.js, though I'm not sure how the image-getting works.

```import React from "react"
import Img from "gatsby-image"

const ListImage = ({title, thumbnail, isTagMode}) => {
  return (
    <div>
      {!isTagMode && <Img fluid={thumbnail} alt={title} />}
      {isTagMode && <img src={thumbnail} alt={title} />}
    </div>
  )
}

export default ListImage```

**Comment by Kallirroi** [comment]
where is the styling of the thumbnails

**Comment by rokeby** [comment]
> where is the styling of the thumbnails

in listItem at bottom

**Comment by Kallirroi** [comment]
![image](https://user-images.githubusercontent.com/10440556/90166434-3f815800-dd68-11ea-86f6-266c2bb2e355.png)

the way I'm getting thumbnails for `tagMode` is different from the way I'm getting it for when we switch across categories - I think thats the problem. I won't go into details as to why I had to do that (no other way) but you might have to define two separate styles, my assumption is that the `gatsby-image` spec is easier to work with (this applies to when we DONT have any tags active) and when we are just getting the raw image file (when we are playing with Tags), the file comes with another native sizing.

**Comment by Kallirroi** [comment]
In the conditional above, when we are under `isTagMode = false`, here is how the image comes through: 
![image](https://user-images.githubusercontent.com/10440556/90166917-f382e300-dd68-11ea-8a29-dc1a0ee0e34f.png)

While on the other case: 
![image](https://user-images.githubusercontent.com/10440556/90167052-2b8a2600-dd69-11ea-8b60-203a5f064bba.png)
