### ISSUE TITLE
Search Results hover effects seem a bit off?

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#63]
![image](https://user-images.githubusercontent.com/10440556/90168559-4067b900-dd6b-11ea-9d9d-693c19fe68f6.png)

**Comment by rokeby** [comment]
updated with 0.3 alpha

<img width="1265" alt="Screenshot 2020-08-14 at 00 21 11" src="https://user-images.githubusercontent.com/23423665/90196580-11c9fc80-ddc4-11ea-8c6b-d52d42b4481d.png">
