### ISSUE TITLE
loading+css issue on front page

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#64]
![Screen Shot 2020-08-13 at 13 49 51](https://user-images.githubusercontent.com/5625731/90169035-077c1400-dd6c-11ea-852a-aee57f44b6cf.png)
sometimes when you load the main page on a breakpoint a bit above mobile, you get this: if you refresh, it goes normal; hard refresh and it goes back to this. My guess is stuff that's being placed relative to other stuff isn't getting loaded properly before the page renders. Maybe only render when elements have all arrived?

Tested this on both Chrome and Firefox, same behaviour.

**Comment by Kallirroi** [comment]
I just created the exact same issue, closing this
