### ISSUE TITLE
calc() functions introduced to many files don't account for mobile

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#67]
![image](https://user-images.githubusercontent.com/10440556/90195478-7fabff00-dd97-11ea-8bd3-fd66b0fb5bd1.png)

**Comment by rokeby** [comment]
had a scroll thru mobile and fixed for reader, don't see it being a problem elsewhere.

**Comment by rokeby** [comment]
think I have resolved the last of these.
