### ISSUE TITLE
slideshows broken again

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#68]
![Screen Shot 2020-08-13 at 21 00 57](https://user-images.githubusercontent.com/5625731/90201244-4d56cd80-dda8-11ea-95dc-0e9ecc90a6f7.png)

there are some slideshows (http://localhost:8000/code-craft-catalogues-arts-in-the-libraries-2019/ is a good example) that are broken while others work normally. About 50% of them are affected. I have a feeling it's to do with lazy loading? 

This is an issue that I fixed with CSS [here](https://github.com/Kallirroi/wordsinspace/commit/31654d0fa50a0ce8d5f1af6f31ca9e3c48742181), but it's broken again. Don't want to break anything else trying to reverse it!

**Comment by samtous** [comment]
@Kallirroi these got changed in [this commit](https://github.com/Kallirroi/wordsinspace/commit/ac7ea298f47dad41d6aab9a00960382685f62c4b), can you remember what you were trying to change?

**Comment by Kallirroi** [comment]
I only prefixed the CSS and fixed the Search?

**Comment by samtous** [comment]
I think things maybe got lost in the merge; will sort this now

**Comment by Kallirroi** [comment]
I applied the fixes in the commit you mention (https://github.com/Kallirroi/wordsinspace/commit/31654d0fa50a0ce8d5f1af6f31ca9e3c48742181) again, lmk if it fixes them?

**Comment by samtous** [comment]
no, it's the same -- just to check: are you seeing the same thing as me on http://localhost:8000/code-craft-catalogues-arts-in-the-libraries-2019/?

**Comment by Kallirroi** [comment]
what are you seeing? I have the old [vc] junk locally since I havent installed clean XML

**Comment by samtous** [comment]
aha I see ok: I'm seeing the same thing as the above screenshot. I think it makes most sense for me to take care of this bit -- idk if you think it's worth running a new install locally? also fine if not and i think i can sort this out

**Comment by Kallirroi** [comment]
is this still a problem?

**Comment by samtous** [comment]
no, working great!!
