### ISSUE TITLE
Links in Related dont work and also have a german language tag?!

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#70]
![image](https://user-images.githubusercontent.com/10440556/90273549-21316000-de2d-11ea-8107-62b82c7553fa.png)

**Comment by rokeby** [comment]
might be a z-index kinda thing, the german tag I will remove, related to CSS hyphenation rules when it comes to Capitalised Words(!)

**Comment by Kallirroi** [comment]
https://github.com/Kallirroi/wordsinspace/commit/97b9751cfb99f04b10c5e2e04ea9b735b90408fa
