### ISSUE TITLE
finalize text for Colophon 

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#75]

**Comment by rokeby** [comment]
![Screenshot 2020-08-17 at 15 16 09](https://user-images.githubusercontent.com/23423665/90406098-95be0600-e09c-11ea-8ee1-d0b1eaee8b9a.png)

Can anyone confirm the details about which version of WIS this is, and so on?

Here's what it says now: I think we should keep it concise, but we can add a short description of ourselves; what else?
