### ISSUE TITLE
Tag Issue: trying to spread non-iterable instance

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#76]
![Screen Shot 2020-08-15 at 16 39 59](https://user-images.githubusercontent.com/5625731/90321298-61204200-df16-11ea-8e21-2b53f8f6cefa.png)

I get this when I click on a tag in the sidebar, tried a couple of times with diff. tags and same issue

**Comment by Kallirroi** [comment]
have you updated `apollo/wrap-page-config.js` ?

**Comment by Kallirroi** [comment]
looks like Vercel version is fine, its your local config most likely.

**Comment by samtous** [comment]
ahh, I didn't realise it had made a friend. updating now
