### ISSUE TITLE
add in CSS styles to replace the old HTML that got taken out

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#77]
![image](https://user-images.githubusercontent.com/5625731/90322879-b6b11a80-df27-11ea-932e-1016c42d3203.png)

I added CSS classes to replace styles that shannon had been using to indent and color/bold/emphasise text. It's up to us how we style it!

**Comment by rokeby** [comment]
making a note that they are in reader.css:366-373

**Comment by rokeby** [comment]
made .indented same colour as bg and .emphasised bold
