### ISSUE TITLE
changing Teaching -> Classes breaks highlighting in Search

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#80]
I've changed the name of the category Teaching to Classes, while leaving the slug as /teaching, as discussed + so as to preserve the url while giving a new name.

This doesn't break the category filter on the right hand side, but does seem to break the highlights and appearence in the search window. Is it possible to make the CSS depend on the slug not the name?

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/5625731/90341068-748ce500-dfca-11ea-84dc-970c54e392af.png">

**Comment by samtous** [comment]
<img width="1064" alt="Screen Shot 2020-08-16 at 14 22 47" src="https://user-images.githubusercontent.com/5625731/90341244-fc272380-dfcb-11ea-8689-430a6906d448.png">
see also

**Comment by rokeby** [comment]
should be fixed will close when deployed
