### ISSUE TITLE
Images sometimes can't be loaded ("mixed (insecure) display content on a secure page")

### ISSUE THREAD

**Issue by rokeby** [Kallirroi/wordsinspace#82]
About half the time I've noticed pages like [this one](https://wordsinspace.vercel.app/publications/fluid-text-total-design-the-woodberry-poetry-room-as-idea-collection-and-place/): the first image loads but subsequent images don't always load. It seems like it might be related to the "mixed (insecure) display content on a secure page"? 

<img width="1544" alt="Screenshot 2020-08-18 at 16 38 02" src="https://user-images.githubusercontent.com/23423665/90534058-30881480-e171-11ea-9e64-a4475404be71.png">
<img width="914" alt="Screenshot 2020-08-18 at 16 38 38" src="https://user-images.githubusercontent.com/23423665/90534129-4695d500-e171-11ea-88ca-0fc7c38dd19b.png">
<img width="670" alt="Screenshot 2020-08-18 at 16 39 15" src="https://user-images.githubusercontent.com/23423665/90534203-5d3c2c00-e171-11ea-992b-a7f3c0b12e0b.png">

**Comment by samtous** [comment]
this is a duplicate issue for #83 -- is it OK if we merge these?

**Comment by rokeby** [comment]
yes, didn't realise!
