### ISSUE TITLE
`list-style-type: none` has been removed from some places 

### ISSUE THREAD

**Issue by rokeby** [Kallirroi/wordsinspace#85]
Not major: some places e.g. [http://localhost:8000/code-craft-catalogues-arts-in-the-libraries-2019/](http://localhost:8000/code-craft-catalogues-arts-in-the-libraries-2019/) (old version [here](https://wordsinspace.net/shannon/code-craft-catalogues-arts-in-the-libraries-2019/)) Shannon had used nested `ul` `li`s with inline `list-style-type: none` basically as an invisible indent. These have been removed meaning we sometimes see double bullet points where an indent was intended. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/23423665/90641182-d2b70380-e228-11ea-8251-e7fe570278cf.png">

**Comment by samtous** [comment]
<img width="483" alt="Screen Shot 2020-08-28 at 01 25 04" src="https://user-images.githubusercontent.com/5625731/91524477-5463fc80-e8cd-11ea-9f1d-e316669c1fa8.png">
thrillingly, this only actually exists in that one place: I'll fix manually on final import :)
