### ISSUE TITLE
accumulating duplicate content with every new XML import

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#92]
![image](https://user-images.githubusercontent.com/10440556/90966428-35fe9b00-e4a0-11ea-91ed-abb20d318670.png)

![image](https://user-images.githubusercontent.com/10440556/90966431-40b93000-e4a0-11ea-9038-e77ad7124fbe.png)

![image](https://user-images.githubusercontent.com/10440556/90966433-457de400-e4a0-11ea-9026-6d42544c52ff.png)

**Comment by Kallirroi** [comment]
Shannon's WP:
![image](https://user-images.githubusercontent.com/10440556/91056449-fc3ea900-e5f3-11ea-9436-adb9c0c73c4b.png)

https://server.wordsinspace.net/wp-admin/
![image](https://user-images.githubusercontent.com/10440556/91056478-05c81100-e5f4-11ea-8b43-613fcb20803f.png)

https://ahole.website/wp-admin/
![image](https://user-images.githubusercontent.com/10440556/91056500-0cef1f00-e5f4-11ea-91d3-4893e68ce43b.png)

**Comment by samtous** [comment]
<img width="618" alt="Screen Shot 2020-08-24 at 19 32 35" src="https://user-images.githubusercontent.com/5625731/91106429-9d535100-e640-11ea-91f3-14789273f729.png">
resolved. first DO import I didn't give it q enough bandwidth and it took two tries, assume that's how it got duplicated. This one has expected number (2 short as not most recent export)
