### ISSUE TITLE
Browser -> Categories buttons are cropped off

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#93]
![image](https://user-images.githubusercontent.com/10440556/91057644-7a4f7f80-e5f5-11ea-9b61-9fc422434b30.png)

**Comment by rokeby** [comment]
weird, in chrome? I am not seeing this in any browser atm

**Comment by Kallirroi** [comment]
Yes in Chrome, Safari + Firefox seem to be OK. If no one else sees it its probably a thing on my end!

**Comment by samtous** [comment]
is this still an issue? looks fine on my chrome on the new deploy

<img width="1522" alt="Screen Shot 2020-08-28 at 16 26 08" src="https://user-images.githubusercontent.com/5625731/91612358-3e951c80-e94b-11ea-89d2-814634292806.png">
