### ISSUE TITLE
Some RelatedItems' title is misplaced

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#94]
![image](https://user-images.githubusercontent.com/10440556/91058200-2db87400-e5f6-11ea-85d5-df6d303da874.png)

**Comment by rokeby** [comment]
Hm, this is due to "uncategorized" label currently being hidden by CSS. But those area all getting recategorised by shannon into blogs and elsewhere, I believe?

**Comment by Kallirroi** [comment]
think we need to remove that Category from the Wordpress, not hide it from CSS.

**Comment by rokeby** [comment]
Yes, of course, just holding off on doing that until we know it's all going somewhere.

**Comment by Kallirroi** [comment]
also a cheap trick for the moment is to set opacity: 0 instead of hiding them - they will still take up vertical space
