### ISSUE TITLE
we are missing captions

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#95]
![image](https://user-images.githubusercontent.com/10440556/91058776-df57a500-e5f6-11ea-8cc7-93ad63103b48.png)

compare to OG:
![image](https://user-images.githubusercontent.com/10440556/91058806-e8e10d00-e5f6-11ea-9258-0de076af431b.png)

Another example
![image](https://user-images.githubusercontent.com/10440556/91058909-0b732600-e5f7-11ea-80f2-98fb67a1d9a5.png)
OG:
![image](https://user-images.githubusercontent.com/10440556/91058937-162dbb00-e5f7-11ea-9c6f-251c2408d86f.png)

**Comment by agnescameron** [comment]
ok i think I know what was causing this: should be fixed for next import.

**Comment by samtous** [comment]
![Screen Shot 2020-08-24 at 19 58 34](https://user-images.githubusercontent.com/5625731/91107836-43ed2100-e644-11ea-8eef-8eda01dc2cd5.png)
fixed on new import

**Comment by samtous** [comment]
AAAgh this is broken again

**Comment by samtous** [comment]
it's fine in the wp editor, but then doesn't appear in the body until you 'update' the page... when it magically appears. FGS. Not sure how to fix this one other than manually

![Screen Shot 2020-08-25 at 16 07 50](https://user-images.githubusercontent.com/5625731/91222551-5b341900-e6ed-11ea-9061-2ee121cda86a.png)
![Screen Shot 2020-08-25 at 16 07 52](https://user-images.githubusercontent.com/5625731/91222554-5bccaf80-e6ed-11ea-8831-5949d35a1361.png)
![Screen Shot 2020-08-25 at 16 08 36](https://user-images.githubusercontent.com/5625731/91222555-5bccaf80-e6ed-11ea-917b-aba682c0cdfd.png)

**Comment by samtous** [comment]
gonna try updating all of the affected posts using php
