### ISSUE TITLE
iOS version of Posts is caca 💩💩💩

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#97]
![image](https://user-images.githubusercontent.com/10440556/91060626-30689880-e5f9-11ea-9c9e-5841f9e711b8.png)

![image](https://user-images.githubusercontent.com/10440556/91060682-3fe7e180-e5f9-11ea-8b4c-5418edb44675.png)

**Comment by rokeby** [comment]
think this is OK now: rogue div wrapper in mobile footer.
