### ISSUE TITLE
inconsistent horizontal spacing in slideshows

### ISSUE THREAD

**Issue by Kallirroi** [Kallirroi/wordsinspace#99]
I assume this has to do with some height/width ratio? in some cases they are spaced far too wide apart and its really hard to know its even a scrollable div

**Comment by rokeby** [comment]
Yes, not sure how to change this. Right now the best way I can see to do it is to give each one a frame the size of the slideshow container, so the tall thin images will end up with more spacing. Perhaps stronger slideshow indication can help.
